### ISSUE TITLE
npm-profile-cli fails to start on Node 6

### ISSUE THREAD

**Issue by jeffora** [npm/npm-profile#1]
I'm not sure if `npm-profile-cli` is supposed to be supported on Node 6, but it currently fails to start due to an `async` function.

If it's not supported, there should probably be some documentation indicating that.

Node: v6.11.0
npm: v5.5.1

**Reproduction:**

1. `npm i npm-profile-cli`
2. `./node_modules/.bin/npm-profile-cli`

Produces:
```
..../node_modules/npm-profile-cli/cmds/util/npmrc.js:14
async function read (file) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jeff/Code/test2/node_modules/npm-profile-cli/cli.js:8:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by iarna** [comment]
Yeah, the CLI is Node.js 8+ because it was optimized for fun (and really only existed to test the feature). The library should be usable back to Node.js 4. Thanks for dropping by! If you feel like putting together a little doc PR I'd be happy to take that.
